--k[x,y,z,u,v,w]/I, where I is generated by x2,xy,yz,z2,zu,u2,uv,vw,
--w2,xz+2zw-uw, zw+xu. 
--This is supposed to be linear up to degree 2,
--but not in degree 3. I took it up to about degree 10.
restart
R=ZZ/32003[x,y,z,u,v,w]
--R=QQ[x,y,z,u,v,w]
I=ideal(x^2,x*y,y*z,z^2,z*u,u^2,u*v,v*w,w^2,x*z+2*z*w-u*w, z*w+x*u)
T=R/I
--betti (F=res(coker vars T, LengthLimit=>3))
betti (F=res(coker vars T))
